---
title: "stat_individual"
author: "Manczinger M."
date: "8/10/2021"
output: html_document
---

The script creates the stat_individual object, which contains naive CD8+ T cell data for Figure 2

```{r}
library(fastmatch)
library(Hmisc)
library(data.table)
library(protr)
library(Rfast)
library(ggplot2)
library(ggpubr)

load("pentamerfreq_tcem") #the file can be downloaded from Mendeley Data (dx.doi.org/10.17632/63xr979845.1) or generated by the dataset_contruction.Rmd script
load("expr_list_tcem") #the file can be downloaded from Mendeley Data (dx.doi.org/10.17632/63xr979845.1) or generated by the creation_of_expr_list_object.Rmd script
subject_metadata = read.delim("subject-metadata.csv", sep = ",", stringsAsFactors = F) #the file was downloaded from https://adaptivepublic.blob.core.windows.net/publishedproject-supplements/covid-2020/ImmuneCODE-MIRA-Release002.zip
peptides = read.delim("peptide-detail.csv", sep = ",", stringsAsFactors = F) #the file was downloaded from https://adaptivepublic.blob.core.windows.net/publishedproject-supplements/covid-2020/ImmuneCODE-MIRA-Release002.zip; the file can be downloaded from Mendeley Data (dx.doi.org/10.17632/63xr979845.1)
rm_aff = readRDS("recogn_matrix_aff.rds") #the file can be downloaded from Mendeley Data (dx.doi.org/10.17632/63xr979845.1). It contains HLA binding data generated by NetMHCPan-4.0
rm_rp = readRDS("recogn_matrix_rp.rds") #the file can be downloaded from Mendeley Data (dx.doi.org/10.17632/63xr979845.1). It contains HLA binding data generated by NetMHCPan-4.0
```


```{r}
peptide_seqs = unique(unlist(strsplit(peptides$Amino.Acids, ",")))
peptide_seqs = peptide_seqs[nchar(peptide_seqs) == 9]

subjects = intersect(subject_metadata$Experiment[subject_metadata$Cohort == "Healthy (No known exposure)" & subject_metadata$Cell.Type == "naive_CD8"], unique(peptides$Experiment))

tcells_found = t(sapply(subjects, FUN = function(x) { 
  !is.na(fmatch(peptide_seqs, unique(unlist(strsplit(peptides$Amino.Acids[peptides$Experiment == x], ",")))))
  }))


colnames(tcells_found) = peptide_seqs

binding_stat_rp = sapply(peptide_seqs, FUN = function(x) {
  temp = lapply(subjects[tcells_found[,x]], FUN = function(y) {
  alleles = gsub(":|\\*", "", substr(subject_metadata[subject_metadata$Experiment == y, 9:14], 1, 7))
  rm_rp[fmatch(alleles, rownames(rm_rp)), x]
  })
  temp = do.call(c, temp)
  temp = names(temp[temp < 0.5])
  temp = table(temp)
  names(temp[temp>1])
})

binding_stat_aff = sapply(peptide_seqs, FUN = function(x) {
  temp = lapply(subjects[tcells_found[,x]], FUN = function(y) {
  alleles = gsub(":|\\*", "", substr(subject_metadata[subject_metadata$Experiment == y, 9:14], 1, 7))
  rm_aff[fmatch(alleles, rownames(rm_aff)), x]
  })
  temp = do.call(c, temp)
  temp = names(temp[temp < 50])
  temp = table(temp)
  names(temp[temp>1])
})

binding_stat_corrected = t(sapply(subjects, FUN = function(x) {
  alleles = gsub(":|\\*", "", substr(subject_metadata[subject_metadata$Experiment == x, 9:14], 1, 7))
  sapply(binding_stat_rp, FUN = function(y) length(intersect(y, alleles)) > 0) & sapply(binding_stat_aff, FUN = function(y) length(intersect(y, alleles)) > 0)
}))

binding_stat_corrected = binding_stat_corrected[,apply(binding_stat_corrected, 2, FUN = function(x) sum(x) > 0)]
tcells_found_corrected = tcells_found[,intersect(colnames(binding_stat_corrected), colnames(tcells_found))]
binding_stat_corrected = binding_stat_corrected[intersect(rownames(tcells_found_corrected), rownames(binding_stat_corrected)),]
tcells_found_corrected = tcells_found_corrected[rownames(binding_stat_corrected),]
tcells_found_corrected = tcells_found_corrected & binding_stat_corrected

tcells_found_corrected = tcells_found_corrected[apply(tcells_found_corrected, 1, FUN = function(x) sum(x) >= 20),]
binding_stat_corrected = binding_stat_corrected[rownames(tcells_found_corrected),]

tcems = substr(colnames(binding_stat_corrected), 4, 8)

tcemfreq = pentamerfreq_tcem[fmatch(tcems, names(pentamerfreq_tcem))]
tcemexpr = sapply(expr_list[fmatch(tcems, names(expr_list))], FUN = function(x) median(x, na.rm = T))
load("tpr_score") #the file can be downloaded from Mendeley Data (dx.doi.org/10.17632/63xr979845.1) or generated by the calculation_of_thymoproteasomal_and_immunoproteasomal_cleavage_scores.Rmd script
tcemthymo = sapply(score_list[fmatch(tcems, names(score_list))], FUN = function(x) median(x, na.rm = T))
load("ipr_score") #the file can be downloaded from Mendeley Data (dx.doi.org/10.17632/63xr979845.1) or generated by the calculation_of_thymoproteasomal_and_immunoproteasomal_cleavage_scores.Rmd script
tcemimmuno = sapply(score_list[fmatch(tcems, names(score_list))], FUN = function(x) median(x, na.rm = T))

exprcutoff = quantile(tcemexpr, na.rm = T, c(0.33, 0.66))
thymocutoff = quantile(tcemthymo, na.rm = T, 0.25)
immunocutoff = quantile(tcemimmuno, na.rm = T, 0.25)
tcemcutoff = 4


stat_individual = t(sapply(rownames(tcells_found_corrected), FUN = function(x) {
  #tcemfreq
  bound_tcemfreq_0_3 = sum(tcemfreq < tcemcutoff & binding_stat_corrected[x,])
  tcell_tcemfreq_0_3 = sum(tcells_found_corrected[x,] & tcemfreq < tcemcutoff & binding_stat_corrected[x,])
  bound_tcemfreq_4_inf = sum(tcemfreq >= tcemcutoff & binding_stat_corrected[x,])
  tcell_tcemfreq_4_inf = sum(tcells_found_corrected[x,] & tcemfreq >= tcemcutoff & binding_stat_corrected[x,])
  
    #expression
  bound_tcemexpr_1st_tertile = sum(tcemexpr < exprcutoff[1] & binding_stat_corrected[x,], na.rm = T)
  tcell_tcemexpr_1st_tertile = sum(tcells_found_corrected[x,] & tcemexpr < exprcutoff[1] & binding_stat_corrected[x,], na.rm = T)
  bound_tcemexpr_2nd_tertile = sum(tcemexpr >= exprcutoff[1] & tcemexpr < exprcutoff[2] & binding_stat_corrected[x,], na.rm = T)
  tcell_tcemexpr_2nd_tertile = sum(tcells_found_corrected[x,] & tcemexpr >= exprcutoff[1] & tcemexpr < exprcutoff[2] & binding_stat_corrected[x,], na.rm = T) 
  bound_tcemexpr_3rd_tertile = sum(tcemexpr >= exprcutoff[2] & binding_stat_corrected[x,], na.rm = T)
  tcell_tcemexpr_3rd_tertile = sum(tcells_found_corrected[x,] & tcemexpr >= exprcutoff[2] & binding_stat_corrected[x,], na.rm = T)
  
  #thymoproteosome_score
  bound_tcemthymo_low = sum(tcemthymo < thymocutoff & binding_stat_corrected[x,], na.rm = T)
  tcell_tcemthymo_low = sum(tcells_found_corrected[x,] & tcemthymo < thymocutoff & binding_stat_corrected[x,], na.rm = T)
  bound_tcemthymo_high = sum(tcemthymo >= thymocutoff & binding_stat_corrected[x,], na.rm = T)
  tcell_tcemthymo_high = sum(tcells_found_corrected[x,] & tcemthymo >= thymocutoff & binding_stat_corrected[x,], na.rm = T)
  
  #immunproteosome_score
  bound_tcemimmuno_low = sum(tcemimmuno < immunocutoff & binding_stat_corrected[x,], na.rm = T)
  tcell_tcemimmuno_low = sum(tcells_found_corrected[x,] & tcemimmuno < immunocutoff & binding_stat_corrected[x,], na.rm = T)
  bound_tcemimmuno_high = sum(tcemimmuno >= immunocutoff & binding_stat_corrected[x,], na.rm = T)
  tcell_tcemimmuno_high = sum(tcells_found_corrected[x,] & tcemimmuno >= immunocutoff & binding_stat_corrected[x,], na.rm = T)
  
  c(bound_tcemfreq_0_3, tcell_tcemfreq_0_3, bound_tcemfreq_4_inf, tcell_tcemfreq_4_inf, bound_tcemexpr_1st_tertile, tcell_tcemexpr_1st_tertile, bound_tcemexpr_2nd_tertile, tcell_tcemexpr_2nd_tertile, bound_tcemexpr_3rd_tertile, tcell_tcemexpr_3rd_tertile, bound_tcemthymo_low, tcell_tcemthymo_low, bound_tcemthymo_high, tcell_tcemthymo_high, bound_tcemimmuno_low, tcell_tcemimmuno_low, bound_tcemimmuno_high, tcell_tcemimmuno_high)
}))

colnames(stat_individual) = c("bound_tcemfreq_0_3", "tcell_tcemfreq_0_3", "bound_tcemfreq_4_inf", "tcell_tcemfreq_4_inf", "bound_tcemexpr_1st_tertile", "tcell_tcemexpr_1st_tertile", "bound_tcemexpr_2nd_tertile", "tcell_tcemexpr_2nd_tertile", "bound_tcemexpr_3rd_tertile", "tcell_tcemexpr_3rd_tertile", "bound_tcemthymo_low", "tcell_tcemthymo_low", "bound_tcemthymo_high", "tcell_tcemthymo_high", "bound_tcemimmuno_low", "tcell_tcemimmuno_low", "bound_tcemimmuno_high", "tcell_tcemimmuno_high")

stat_individual = cbind(stat_individual, tcemfreq_0_3 = stat_individual[,"tcell_tcemfreq_0_3"]/ stat_individual[,"bound_tcemfreq_0_3"],
                        tcemfreq_4_inf = stat_individual[,"tcell_tcemfreq_4_inf"]/ stat_individual[,"bound_tcemfreq_4_inf"],
                        expr_1st_tertile = stat_individual[,"tcell_tcemexpr_1st_tertile"]/ stat_individual[,"bound_tcemexpr_1st_tertile"],
                        expr_2nd_tertile = stat_individual[,"tcell_tcemexpr_2nd_tertile"]/ stat_individual[,"bound_tcemexpr_2nd_tertile"],
                        expr_3rd_tertile = stat_individual[,"tcell_tcemexpr_3rd_tertile"]/ stat_individual[,"bound_tcemexpr_3rd_tertile"],
                        thymo_low = stat_individual[,"tcell_tcemthymo_low"]/ stat_individual[,"bound_tcemthymo_low"],
                        thymo_high = stat_individual[,"tcell_tcemthymo_high"]/ stat_individual[,"bound_tcemthymo_high"],
                        immuno_low = stat_individual[,"tcell_tcemimmuno_low"]/ stat_individual[,"bound_tcemimmuno_low"],
                        immuno_high = stat_individual[,"tcell_tcemimmuno_high"]/ stat_individual[,"bound_tcemimmuno_high"])

stat_individual = as.data.frame(stat_individual) #the file is also on github
```

